### ISSUE TITLE
Initial System Settings Error

### ISSUE THREAD

**Issue by nsauter** [deeztek/Hermes-Secure-Email-Gateway#1]
Hey,

im currently testing this secure email gateway. Installation went pretty smooth but now im facing a error in the initial system settings page.

Postmaster E-Mail: postmaster@njsh.de
Admin E-Mail: XXXXX@gmail.com

When i select "Save Settings" the system prompts: The Postmaster E-mail Address must be part of a domain that this system relays.

How can i fix this?

**Comment by deeztek** [comment]
Hi,

Please put "Postmaster E-mail Address" field back to "postmaster@domain.tld", fill in the Database Credentials and click on "Save Settings".

You cannot change the Postmaster E-mail Address to postmaster@njsh.de until you setup your njsh.de as a Relay Domain first. 

If you are not already using it, check out the "Getting Started" guide at https://www.deeztek.com/documentation/hermes-seg-documentation/hermes-seg-administrator-guide/getting-started/
