### ISSUE TITLE
New Build

### ISSUE THREAD

**Issue by tlynn1985** [deeztek/Hermes-Secure-Email-Gateway#24]
Newest build will stall out on fresh installation during mysql when running the install script.
![image](https://user-images.githubusercontent.com/54050659/136673465-cb8bb1bc-3ad0-473f-9963-477b1f28b86b.png)

**Comment by deeztek** [comment]
Hi it's not immediately obvious what the problem is. Can you post the install_log-$TIMESTAMP.log in its entirety? Also what Ubuntu version are you using and did you utilize special characters for your mysql passwords?

Thanks

**Comment by deeztek** [comment]
Well we did make some changes to the table character sets on the newest build. Maybe that's what causing the problem. I'll build a new vm and see if I can figure out the issue. Sorry about that.
