### ISSUE TITLE
Error step 61 of 61: 1, occured during ensuring Hermes SEG permissions are set correctly

### ISSUE THREAD

**Issue by ictinc** [deeztek/Hermes-Secure-Email-Gateway#4]
Hi there,
I'd like to evaluate Hermes SEG however each time diring install the installation quits all of a sudden. The log file shows the following on the last line;
Error step 61 of 61: 1, occured during ensuring Hermes SEG permissions are set correctly

This happens right after the expected OpenDMARC error.

The server is a VM on on ESXI.
It's a new install and has Ubuntu 18.04 installed with the latest updates, 10Gb RAM, 1x 16Gb disk and 1x 250Gb disk.

I wasn't able to find any documents on the forum so I'm not really sure where to go from here. Any support would be much appreciated.

Kind regards,
Ronald.

**Comment by ictinc** [comment]
I went through the install.sh file and did the last steps of the file manually.
I was able to enter those comments without getting any error messages and after performing a reboot everything seemed to work.

**Comment by deeztek** [comment]
> Hi there,
> I'd like to evaluate Hermes SEG however each time diring install the installation quits all of a sudden. The log file shows the following on the last line;
> Error step 61 of 61: 1, occured during ensuring Hermes SEG permissions are set correctly
> 
> This happens right after the expected OpenDMARC error.
> 

Hi Ronald,

This is the right place to post bugs. Would you happen to have the install_log-$TIMESTAMP.log file that got created when you run the install script? 

Thanks

**Comment by deeztek** [comment]
unable to duplicate

**Comment by deeztek** [comment]
Uploaded patch **abe7a52_issue_6.sh** to address the issue:

[https://github.com/deeztek/Hermes-Secure-Email-Gateway/blob/master/patches/abe7a52_issue_6.sh](https://github.com/deeztek/Hermes-Secure-Email-Gateway/blob/master/patches/abe7a52_issue_6.sh)
