### ISSUE TITLE
Migrate away from ExtremeShok clamav-unofficial-sigs

### ISSUE THREAD

**Issue by deeztek** [deeztek/Hermes-Secure-Email-Gateway#47]
ExtremeShok clamav-unofficial-sigs looks like an abandoned project. Replace with Fangfrisch

**Comment by JReming85** [comment]
Others are recommending https://github.com/rseichter/fangfrisch as a good long term replacement

**Comment by deeztek** [comment]
Thanks for the recommendation. We looked at it already and we decided to build our own.

**Comment by deeztek** [comment]
Change of plans. We have decided to go with Fanfrisch instead of re-inventing the wheel. Hermes SEG build-240815 removes ExtremeShok clamav-unofficial-sigs and replaces with Fangfrisch.
