### ISSUE TITLE
Script Fails on First Step

### ISSUE THREAD

**Issue by justinharbour** [deeztek/Hermes-Secure-Email-Gateway#66]
When running the script, it fails on the first step and throws an HTTP error 100 for Boxes.

```
root@secure-mail:/tmp/Hermes-Secure-Email-Gateway# sudo ./ubuntu_hermes_install.sh
Installing Boxes Prerequisite
Error 100, occurred Installing Boxes Prerequisite
```

I have received the below output on both fully updated versions of Ubuntu 20.04, 24.04 and Debian 12. Is this a known issue?

**Comment by justinharbour** [comment]
Oddly enough, I was able to isolate this issue to the fact that I was running the instance on a Hetzner Cloud server. I was able to successfully bypass this error on Vultr Cloud instead.

**Comment by deeztek** [comment]
Strange indeed.  Glad you got it working.
